### ISSUE TITLE
Fails to compile on Ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by Anas-Shrinah** [JoanEspasa/rantanplan-public#1]
Hi,

After compiling the source code with make with gcc version 5.4.0 20160609 , I got an error in compiling "encodingUFVisitorZ3.cpp" in line 519. To see through the compilation I commented out the source of the error, the contents of the function "  ‘encodingUFVisitorZ3::z3_assert_str(std::__cxx11::string, z3::context*, z3::solver*)’" . Then the build worked. But I am afraid that this might cause the planner to work improperly. Could you please advise a proper fix to this issue.

This the detailed error:

g++  -DYICES2 -I./libantlr3c-3.4_64b/include/ -I../solvers/z3-4.8.8-x64-ubuntu-16.04/include -I../solvers/yices-2.6.2/include -fpermissive -Wall -std=c++11  -O3  -c encodingUFVisitorZ3.cpp
encodingUFVisitorZ3.cpp: In member function ‘void encodingUFVisitorZ3::z3_assert_str(std::__cxx11::string, z3::context*, z3::solver*)’:
encodingUFVisitorZ3.cpp:519:32: error: cannot convert ‘Z3_ast_vector {aka _Z3_ast_vector*}’ to ‘Z3_ast {aka _Z3_ast*}’ in initialization
                 &v_func_decl[0]);
                                ^
In file included from ../solvers/z3-4.8.8-x64-ubuntu-16.04/include/z3.h:27:0,
                 from ../solvers/z3-4.8.8-x64-ubuntu-16.04/include/z3++.h:28,
                 from encodingUFVisitorZ3.h:4,
                 from encodingUFVisitorZ3.cpp:1:
../solvers/z3-4.8.8-x64-ubuntu-16.04/include/z3_macros.h:20:39: note: class type ‘_Z3_ast_vector’ is incomplete
 #define DEFINE_TYPE(T) typedef struct _ ## T *T
                                       ^
../solvers/z3-4.8.8-x64-ubuntu-16.04/include/z3_api.h:29:1: note: in expansion of macro ‘DEFINE_TYPE’
 DEFINE_TYPE(Z3_ast_vector);
 ^
Makefile:105: recipe for target 'encodingUFVisitorZ3.o' failed
make: *** [encodingUFVisitorZ3.o] Error 1

Thanks
